version: "3.8"

services:
  db:
    image: postgres:14.2
    networks:
      - crowdproject
    volumes: 
      - data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    networks:
      - crowdproject
    links:
      - db:db
    command: >
      sh -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"

volumes:
  data:
    name: crowds

networks:
  crowdproject:
    driver: bridge