version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.3
      - image: cimg/postgres:14.2
        environment:
          NAME: $NAME
          USER: $USER
          PASSWORD: $PASSWORD
          HOST: $HOST
          SECRET_KEY: $DJANGO_SECRET_KEY
    steps:
      - checkout 
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup env
          command: |
            echo 'export IMG_TAG=${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMG_NAME=python-circleci-docker' >> $BASH_ENV
            virtualenv crowdproject
            . crowdproject/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . crowdproject/bin/activate
            python manage.py test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . crowdproject/bin/activate
            docker build -t kris719/$IMG_NAME:$IMG_TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push kris719/$IMG_NAME:$IMG_TAG

workflows:
  main:
    jobs:
      - build
          context: crowdproject