# Generated by Django 3.2 on 2021-04-26 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('name', models.CharField(help_text='Trail Name', max_length=100, unique=True)),
                ('region', models.CharField(choices=[('OP', 'Olympic Peninsula'), ('NC', 'North Cascades'), ('CC', 'Central Cascades'), ('SQ', 'Snoqualmie'), ('SC', 'South Cascades'), ('EW', 'Eastern Washington'), ('CW', 'Central Washington'), ('WW', 'Western Washington Lowlands'), ('SW', 'Southwest Washington')], help_text='Geographic region in Washington where trail is located', max_length=2)),
                ('coordinates', models.CharField(help_text='Geographic coordinates searchable via Google Maps', max_length=25)),
                ('length', models.DecimalField(blank=True, decimal_places=1, help_text='From 0.0 to 999.9 miles', max_digits=4)),
                ('elevation_gain', models.IntegerField(blank=True, verbose_name='Elevation Gain')),
            ],
        ),
        migrations.CreateModel(
            name='Trailhead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('coordinates', models.CharField(help_text='Geographic coordinates searchable via Google Maps', max_length=25)),
                ('pkg_type', models.CharField(blank=True, choices=[('UL', 'Unpaved Lot'), ('PL', 'Paved Lot'), ('S', 'Street/Road'), ('P', 'Designated Pullout/Shoulder')], help_text='Type of Parking at Trailhead', max_length=2)),
                ('pkg_capacity', models.IntegerField(blank=True, help_text='Approximate number of cars capable of parking at trailhead lot', verbose_name='Parking Capacity')),
                ('bathroom', models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed'), ('N', 'None')], help_text='Is there a bathroom at the trailhead?', max_length=1)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('date_hiked', models.DateField(help_text='What date was the hike?')),
                ('day_hiked', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Su', 'Sunday')], help_text='What day of the week was the hike?', max_length=2)),
                ('trail_begin', models.TimeField(help_text='What time did the hike begin?')),
                ('trail_end', models.TimeField(help_text='What time did the hike end?')),
                ('bathroom', models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed'), ('N', 'None')], help_text='Is there a bathroom at the trailhead?', max_length=1)),
                ('pkg_location', models.CharField(choices=[('UL', 'Unpaved Lot'), ('PL', 'Paved Lot'), ('S', 'Street/Road'), ('P', 'Designated Pullout/Shoulder')], help_text='Where did you park at the trailhead?', max_length=2)),
                ('pkg_estimate_begin', models.IntegerField(help_text='Approximate parking capacity full at trailhead arrival', verbose_name='Percentage Capacity Start')),
                ('pkg_estimate_end', models.IntegerField(help_text='Approximate parking capacity full at trailhead departure', verbose_name='Percentage Capacity End')),
                ('cars_seen', models.IntegerField(help_text='Most cars seen at arrival/departure', verbose_name='Cars seen')),
                ('people_seen', models.IntegerField(help_text='Approximate number of people encountered on trail', verbose_name='People seen')),
                ('horses_seen', models.BooleanField()),
                ('dogs_seen', models.BooleanField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
                ('trailhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trailhead')),
            ],
        ),
    ]
