# Generated by Django 4.0.4 on 2022-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='trailhead',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
