# Generated by Django 4.0.4 on 2022-06-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='dogs_allowed',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='horses_allowed',
        ),
    ]
