# Generated by Django 3.2 on 2021-04-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elevation Gain'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='From 0.0 to 999.9 miles', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='pkg_capacity',
            field=models.IntegerField(blank=True, help_text='Approximate number of cars capable of parking at trailhead lot', null=True, verbose_name='Parking Capacity'),
        ),
    ]
