# Generated by Django 3.2 on 2021-04-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_auto_20210426_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed'), ('N', 'None')], help_text='Is there a bathroom at the trailhead?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed'), ('N', 'None')], help_text='Is there a bathroom at the trailhead?', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='pkg_type',
            field=models.CharField(blank=True, choices=[('UL', 'Unpaved Lot'), ('PL', 'Paved Lot'), ('S', 'Street/Road'), ('P', 'Designated Pullout/Shoulder')], help_text='Type of Parking at Trailhead', max_length=2, null=True),
        ),
    ]
