# Generated by Django 4.0.4 on 2022-05-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_region_slug_trail_slug_trailhead_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='slug',
            new_name='region_slug',
        ),
        migrations.RenameField(
            model_name='trail',
            old_name='slug',
            new_name='trail_slug',
        ),
        migrations.RenameField(
            model_name='trailhead',
            old_name='slug',
            new_name='trailhead_slug',
        ),
    ]
