# Generated by Django 4.0.4 on 2022-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_rename_slug_region_region_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
