# Generated by Django 3.2 on 2021-05-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_auto_20210426_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(blank=True, help_text='From trailhead to highest point of trail', null=True, verbose_name='Elevation Gain'),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='name',
            field=models.CharField(help_text='Name of Trailhead', max_length=50, unique=True),
        ),
    ]
