# Generated by Django 4.0.4 on 2022-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_alter_region_region_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='trailhead_slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
