# Generated by Django 3.2 on 2021-05-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_auto_20210511_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='trailhead',
            name='bathroom',
        ),
        migrations.AddField(
            model_name='report',
            name='access',
            field=models.CharField(blank=True, choices=[('FS', 'Forest Service Road'), ('P', 'Paved Road')], help_text='How is the trailhead accessed?', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='bathroom_status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed')], help_text='Is the bathroom open?', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('P', 'Portable/Outhouse'), ('FP', 'Fixed Building, Pit'), ('FR', 'Fixed Building with plumbing')], help_text='Is there a bathroom at the trailhead?', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='trailhead',
            name='access',
            field=models.CharField(blank=True, choices=[('FS', 'Forest Service Road'), ('P', 'Paved Road')], help_text='How is the trailhead accessed?', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='trailhead',
            name='bathroom_status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Closed')], help_text='Is the bathroom open?', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='trailhead',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('P', 'Portable/Outhouse'), ('FP', 'Fixed Building, Pit'), ('FR', 'Fixed Building with plumbing')], help_text='Is there a bathroom at the trailhead?', max_length=2, null=True),
        ),
    ]
