# Generated by Django 4.0.4 on 2022-05-25 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_alter_trail_trail_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailhead',
            name='pkg_capacity',
            field=models.IntegerField(blank=True, help_text='Approximate number of cars capable of parking at trailhead lot', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Parking capacity'),
        ),
    ]
