# Generated by Django 3.2 on 2021-05-15 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_auto_20210513_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='From 0.0 to 999.9 miles', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.CharField(choices=[('OP', 'Olympic Peninsula'), ('NC', 'North Cascades'), ('CC', 'Central Cascades'), ('SQ', 'Snoqualmie'), ('SC', 'South Cascades'), ('WW', 'Western Washington Lowlands'), ('EW', 'Eastern Washington'), ('CW', 'Central Washington'), ('SW', 'Southwest Washington')], help_text='Geographic region in Washington where trail is located', max_length=2),
        ),
    ]
