# Generated by Django 4.0.4 on 2022-05-27 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_alter_trailhead_pkg_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='dogs_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='horses_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailhead',
            name='access_condition',
            field=models.CharField(blank=True, choices=[('I', 'Impassable'), ('P+', 'Many potholes'), ('P', 'Potholes'), ('P-', 'Occasional potholes'), ('G', 'Good')], help_text='Condition of road to trailhead', max_length=2, null=True, verbose_name='Road access condition'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pkg_estimate_begin',
            field=models.IntegerField(help_text='Approximate parking capacity full at trailhead arrival', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Capacity Start'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pkg_estimate_end',
            field=models.IntegerField(help_text='Approximate parking capacity full at trailhead departure', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Capacity End'),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='pkg_capacity',
            field=models.IntegerField(blank=True, help_text='Approximate number of cars capable of parking at trailhead lot', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Parking capacity'),
        ),
    ]
