# Generated by Django 3.2 on 2021-05-15 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_auto_20210514_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cars_seen',
            field=models.IntegerField(help_text='Most cars seen at arrival/departure', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cars seen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='people_seen',
            field=models.IntegerField(help_text='Approximate number of people encountered on trail', validators=[django.core.validators.MinValueValidator(0)], verbose_name='People seen'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pkg_estimate_begin',
            field=models.IntegerField(help_text='Approximate parking capacity full at trailhead arrival', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Capacity Start'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pkg_estimate_end',
            field=models.IntegerField(help_text='Approximate parking capacity full at trailhead departure', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Capacity End'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(blank=True, help_text='From trailhead to highest point of trail', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Elevation Gain'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='From 0.1 to 999.9 miles', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='pkg_capacity',
            field=models.IntegerField(blank=True, help_text='Approximate number of cars capable of parking at trailhead lot', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Parking Capacity'),
        ),
    ]
