# Generated by Django 4.0.4 on 2022-05-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_trail_dogs_allowed_trail_horses_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dogs_seen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='horses_seen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
