# Generated by Django 3.2 on 2021-05-18 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_auto_20210514_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pkg_estimate_begin',
            field=models.IntegerField(help_text='Approximate parking capacity full at trailhead arrival', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentage Capacity Start'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pkg_estimate_end',
            field=models.IntegerField(help_text='Approximate parking capacity full at trailhead departure', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentage Capacity End'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pkg_location',
            field=models.CharField(choices=[('UL', 'Unpaved Lot'), ('PL', 'Paved Lot'), ('S', 'Street/Road'), ('P', 'Designated Pullout/Shoulder')], help_text='Where did you park at the trailhead?', max_length=2, verbose_name='Type of Parking'),
        ),
    ]
