# Generated by Django 3.2 on 2022-06-01 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0009_alter_trailhead_access_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailhead',
            name='access_distance',
            field=models.CharField(blank=True, help_text='If accessed via service road, length of service road from paved road to trailhead', max_length=20, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
