# Generated by Django 3.2 on 2022-06-01 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_alter_trailhead_access_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailhead',
            name='access_distance',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='If accessed via service road, length of service road from paved road to trailhead', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
