# Generated by Django 3.2 on 2021-05-25 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_auto_20210524_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailhead',
            name='access_distance',
            field=models.IntegerField(blank=True, help_text='If accessed via service road, length of service road from paved road to trailhead', null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
