# Generated by Django 3.2 on 2021-12-01 23:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_alter_trailhead_access_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('OP', 'Olympic Peninsula'), ('NC', 'North Cascades'), ('CC', 'Central Cascades'), ('SQ', 'Snoqualmie'), ('SC', 'South Cascades'), ('WW', 'Western Washington Lowlands'), ('EW', 'Eastern Washington'), ('CW', 'Central Washington'), ('SW', 'Southwest Washington')], help_text='Region Name', max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.region'),
        ),
    ]
