# Generated by Django 3.2 on 2021-12-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0013_auto_20211201_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trails.region'),
        ),
    ]
