# Generated by Django 3.2 on 2021-12-02 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_report_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailhead',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trails.region'),
        ),
    ]
