# Generated by Django 3.2 on 2021-12-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0016_auto_20211202_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trailheads',
            field=models.ManyToManyField(blank=True, related_name='trails', to='trails.Trailhead'),
        ),
    ]
