# Generated by Django 3.2 on 2021-12-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0017_alter_trail_trailheads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='trailheads',
        ),
        migrations.AddField(
            model_name='trailhead',
            name='trails',
            field=models.ManyToManyField(related_name='trailheads', to='trails.Trail'),
        ),
    ]
