# Generated by Django 3.2 on 2021-12-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0018_auto_20211206_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.region'),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.region'),
        ),
    ]
