# Generated by Django 3.2 on 2021-12-10 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0019_auto_20211209_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.IntegerField(blank=True, help_text='From trailhead to highest point of trail', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Elevation Gain'),
        ),
    ]
