# Generated by Django 3.2 on 2021-12-10 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0020_alter_trail_elevation_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='elevation_gain',
            field=models.IntegerField(blank=True, help_text='From trailhead to highest point of trail', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Elevation Gain'),
        ),
        migrations.AddField(
            model_name='report',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='From 0.1 to 999.9 miles', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
