# Generated by Django 3.2 on 2021-12-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0021_auto_20211209_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='elevation_gain',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='length',
        ),
        migrations.AddField(
            model_name='trail',
            name='elevation_gain_json',
            field=models.JSONField(blank=True, help_text='From trailhead to highest point of trail', null=True, verbose_name='Elevation Gain'),
        ),
        migrations.AddField(
            model_name='trail',
            name='length_json',
            field=models.JSONField(blank=True, help_text='From 0.1 to 999.9 miles', null=True, verbose_name='Trail length'),
        ),
    ]
